import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./components/Carousel.css";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/Navbar";

import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-col min-h-screen">
        <div id="menu-portal" />
        <StoreProvider>
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
